# Generated by Django 2.2 on 2020-04-06 02:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HorarioGeneral',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('carrera', models.CharField(max_length=30, null=True)),
                ('horario', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='HorarioParticular',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('horario', models.TextField(blank=True)),
                ('puntuacion', models.IntegerField(null=True)),
                ('creditos', models.IntegerField(null=True)),
                ('carrera', models.CharField(max_length=30, null=True)),
            ],
        ),
    ]
